const fs = require('fs');

// Command line arguments ko read karna (jo Render bhejayega)
const args = process.argv.slice(2);
let kitchenId = 'default';
let appName = 'Cloud Kitchen';

args.forEach(arg => {
    if (arg.startsWith('--id=')) kitchenId = arg.split('=')[1].replace(/"/g, '');
    if (arg.startsWith('--name=')) appName = arg.split('=')[1].replace(/"/g, '');
});

console.log(`⚙️ Customizing Flutter App for: ${appName} (ID: ${kitchenId})`);

// 1. Flutter App ke andar Kitchen ID aur Name ka ek file banana
// Jisko aap Flutter UI me use kar sakte hain
const configDir = './lib';
if (!fs.existsSync(configDir)) fs.mkdirSync(configDir);

const configContent = `// AUTO-GENERATED BY CLOUD APP FACTORY
class AppConfig {
  static const String kitchenId = "${kitchenId}";
  static const String appName = "${appName}";
}
`;
fs.writeFileSync(`${configDir}/app_config.dart`, configContent);
console.log('✅ Created lib/app_config.dart with Kitchen ID');

// 2. Android App ka Asli Naam (Launcher Name) Change Karna
const manifestPath = './android/app/src/main/AndroidManifest.xml';
if (fs.existsSync(manifestPath)) {
    let manifest = fs.readFileSync(manifestPath, 'utf8');
    // Android label ko replace karna
    manifest = manifest.replace(/android:label="[^"]*"/, `android:label="${appName}"`);
    fs.writeFileSync(manifestPath, manifest);
    console.log(`✅ Changed Android App Name to: ${appName}`);
} else {
    console.log('⚠️ AndroidManifest.xml not found, skipping name change.');
}

console.log('🎉 App Customization Complete! Ready for APK Build.');