name: rasoisathi_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  webview_flutter: ^4.14.1
  url_launcher: ^6.2.5  # Ye nayi line add karein

# Ek hi dev_dependencies block hona chahiye
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

# Icon generator ki settings (sabse aakhir me)
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"